# Generated by Django 3.1.3 on 2021-10-01 03:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PxPUC", "0004_searchquery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchquery",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
