# Generated by Django 3.1.3 on 2021-11-04 15:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("PxPUC", "0006_auto_20211104_1528"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="location",
        ),
    ]
