# Generated by Django 3.1.3 on 2021-11-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PxPUC", "0007_remove_question_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="a",
            field=models.CharField(default="", max_length=2000),
        ),
    ]
