# Generated by Django 3.1.3 on 2022-08-12 22:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("PxPUC", "0008_auto_20211130_1541"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="searchquery",
            options={"verbose_name_plural": "Search Queries"},
        ),
    ]
