# Generated by Django 3.1.3 on 2022-03-14 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("PxPUC", "0008_auto_20211130_1541"),
        ("PxPUC", "0005_auto_20211007_2014"),
    ]

    operations = []
