# Generated by Django 3.1.3 on 2022-10-26 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("PxPUC", "0009_auto_20220812_2225"),
        ("PxPUC", "0009_merge_20220314_1816"),
    ]

    operations = []
