# Generated by Django 3.1.3 on 2022-11-01 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("PxPUC", "0009_merge_20220314_1816"),
        ("PxPUC", "0009_auto_20220812_2225"),
    ]

    operations = []
