# Generated by Django 3.1.3 on 2023-04-11 23:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("PxPUC", "0010_merge_20221101_1816"),
        ("PxPUC", "0010_merge_20221026_1833"),
    ]

    operations = []
