# Generated by Django 3.1.3 on 2022-10-21 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("PxPUC", "0010_merge_20221014_1752"),
        ("PxPUC", "0010_merge_20221019_1515"),
    ]

    operations = []
