# Generated by Django 3.1.3 on 2023-04-10 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PxPUC', '0010_department_keyword_mastercontract_municipality_provision'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='mContractObj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dept', to='PxPUC.mastercontract'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='departmentObj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='munici', to='PxPUC.department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='fullOfficers2019',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='partOfficers2019',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='acreArea',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='department',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='nonWhitePop2010',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='sqMiArea',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='provision',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
