# Generated by Django 3.1.3 on 2023-05-08 15:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("PxPUC", "0011_merge_20230411_2328"),
        ("PxPUC", "0011_auto_20230410_1839"),
    ]

    operations = []
